# Generated by Django 5.2.5 on 2025-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registar',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
